version: '3'
services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
    environment:
      - NGINX_RTMP_FILESDIR=/tmp/nginx-rtmp-files
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./rtmp-files:/tmp/nginx-rtmp-files